# Generated by Django 3.1.12 on 2025-05-05 12:01

import bson.objectid
import django.core.validators
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('user_type', models.CharField(choices=[('doctor', 'doctor'), ('patient', 'patient')], default='patient', max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('booking_id', models.CharField(max_length=50, unique=True)),
                ('patient_id', models.CharField(max_length=50)),
                ('doctor_id', models.CharField(max_length=50)),
                ('timeslot_id', models.CharField(max_length=50)),
                ('date', models.DateField(null=True)),
                ('start_time', models.CharField(max_length=50)),
                ('end_time', models.CharField(max_length=50)),
                ('appointment_status', models.CharField(choices=[('confirmed', 'confirmed'), ('cancelled', 'cancelled'), ('completed', 'completed')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('doctor_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('cnic', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='CNIC must be exactly 13 digits (numbers only).', regex='^\\d{13}$')])),
                ('picture', models.URLField(blank=True, null=True)),
                ('education', djongo.models.fields.JSONField()),
                ('specialization', models.CharField(max_length=100)),
                ('hospital_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('cnic', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='CNIC must be exactly 13 digits (numbers only).', regex='^\\d{13}$')])),
                ('address', models.TextField(null=True)),
                ('blood_type', models.CharField(blank=True, max_length=3, null=True)),
                ('emergency_contact', models.CharField(max_length=20)),
                ('medical_history', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('timeslot_id', models.CharField(max_length=50, unique=True)),
                ('doctor_id', models.CharField(max_length=50)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
            ],
        ),
    ]